Repository EthicApp-Development/ethicapp-main, pull requests merged in 2023-10, with the labels that each got.

#254 [ethicapp-v2] Issue #252: Arreglo de elementos duplicados tras merge rama frontend_controllers_refactoring
  ethicapp/frontend/assets/css/custom.css
  ethicapp/frontend/assets/css/main.css
  ethicapp/frontend/assets/i18n/EN_US/english.json
  ethicapp/frontend/assets/i18n/ES_CL/spanish.json
  ethicapp/frontend/assets/js/controllers/teacher/confirm_modal_controller.js
  ethicapp/frontend/assets/js/controllers/teacher/monitor_activity_controller.js
  ethicapp/frontend/assets/js/ngmodules/teacher/teacher_admin.mjs
  ethicapp/frontend/static/end-activity-dialog.html
  ethicapp/frontend/views/ethics.ejs
  ethicapp/frontend/views/forgot-pass.ejs
  ethicapp/frontend/views/partials/profile.html
  ethicapp/frontend/views/partials/teacher/activity.html
  ethicapp/frontend/views/roles.ejs
Labels: bug

#246 [ethicapp-v2] Issue #251: Crear endpoints para el modelo teacher_account_requests
  ethicapp/backend/controllers/users.js
  ethicapp/frontend/assets/i18n/EN_US/english.json
  ethicapp/frontend/assets/i18n/ES_CL/spanish.json
  ethicapp/frontend/views/login.ejs
  postgres-db/schema/create_37.sql
Labels: new feature

#242 [admin-panel] Issue #195: first commit requests view
  .env
  admin-panel/package.json
  admin-panel/src/App.js
  admin-panel/src/components/BoxGrid.js
  admin-panel/src/components/NavBars.js
  admin-panel/src/languages/EN_US/english.json
  admin-panel/src/languages/ES_CL/spanish.json
  admin-panel/src/pages/TeacherAccountRequest.js
  admin-panel/src/pages/TeacherAccountRequests.js
  docker-compose-image-renewal.yml
  docker-compose.yml
  ethicapp/app.js
  ethicapp/package.json
Labels: new feature

#256 [ethicapp-v2] Issue #255: Duplicado log6 vista Login
  ethicapp/frontend/views/login.ejs
Labels: bug

#261 [Admin-Panel] Actualización de base de datos y registro de evento.
  admin-panel/.dockerignore
  admin-panel/Dockerfile
  admin-panel/package.json
  admin-panel/production.Dockerfile
  admin-panel/src/components/APICommunication.js
  admin-panel/src/components/GraphDataParser.js
  admin-panel/src/components/InstitutionForm.js
  admin-panel/src/components/ReportGraphBox.js
  admin-panel/src/components/ReportOptionsBox.js
  admin-panel/src/languages/EN_US/english.json
  admin-panel/src/languages/ES_CL/spanish.json
  admin-panel/src/pages/Institution.js
  admin-panel/src/pages/Reports.js
  admin-panel/src/pages/SingleReport.js
  docker-compose.production.yaml
  docker-compose.yml
  ethicapp/app.js
  ethicapp/backend/controllers/admin-panel-api.js
  ethicapp/backend/controllers/analysis.js
  ethicapp/backend/controllers/sessions.js
  ethicapp/backend/controllers/users.js
  package.json
  postgres-db/report_seed
  postgres-db/schema/create_35.sql
  postgres-db/schema/create_38.sql
  postgres-db/seeds/development/02_institution.sql
  postgres-db/seeds/development/04_report_description.sql
  web-nginx/nginx.conf
Labels: enhancement

#260 [ethicapp-v2] Issue #69: Texto de botón para mostrar diseño no cambia
  ethicapp/frontend/assets/i18n/EN_US/english.json
  ethicapp/frontend/assets/i18n/ES_CL/spanish.json
  ethicapp/frontend/assets/i18n/en.json
  ethicapp/frontend/assets/i18n/es.json
  ethicapp/frontend/views/partials/teacher/activity.html
Labels: enhancement

#262 [admin-panel] Login, Cache y subir archivos
  admin-panel/package.json
  admin-panel/src/App.js
  admin-panel/src/components/APICommunication.js
  admin-panel/src/components/InstitutionForm.js
  admin-panel/src/components/NavBars.js
  admin-panel/src/components/ProtectedRoute.js
  admin-panel/src/pages/Institution.js
  admin-panel/src/pages/Login.js
  docker-compose.production.yaml
  docker-compose.yml
  ethicapp/app.js
  ethicapp/backend/controllers/admin-panel-api.js
  ethicapp/backend/controllers/users.js
  ethicapp/package.json
  web-nginx/nginx.conf
Labels: enhancement

#268 [admin-panel] Lógica Api request con o sin puerto
  .env
  admin-panel/Dockerfile
  admin-panel/production.Dockerfile
  admin-panel/src/components/APICommunication.js
  admin-panel/src/components/InstitutionForm.js
  admin-panel/src/pages/Institution.js
  admin-panel/src/pages/Login.js
  docker-compose.production.yaml
  docker-compose.yml
  ethicapp/production.Dockerfile
Labels: bug

#269 [admin-panel] Issue #270: Centralizar uso de Axios
  .env
  admin-panel/src/components/APICommunication.js
  admin-panel/src/pages/TeacherAccountRequest.js
  admin-panel/src/pages/TeacherAccountRequests.js
  ethicapp/backend/controllers/users.js
  ethicapp/frontend/assets/i18n/EN_US/english.json
  ethicapp/frontend/assets/i18n/ES_CL/spanish.json
  ethicapp/frontend/assets/i18n/en.json
  ethicapp/frontend/assets/i18n/es.json
Labels: enhancement

#278 [admin-panel] Google login fix & api key name change
  admin-panel/src/components/APICommunication.js
  admin-panel/src/components/NavBars.js
  admin-panel/src/components/ProtectedRoute.js
  admin-panel/src/pages/Login.js
  ethicapp/backend/controllers/users.js
Labels: bug

#273 [admin-panel] Issue #272: Rechazar e Ignorar solicitudes de cuenta de profesor
  admin-panel/src/components/APICommunication.js
  admin-panel/src/languages/EN_US/english.json
  admin-panel/src/languages/ES_CL/spanish.json
  admin-panel/src/pages/TeacherAccountRequest.js
  admin-panel/src/pages/TeacherAccountRequests.js
  ethicapp/backend/controllers/users.js
Labels: new feature

#266 [ethicapp-v2] Issue #265: Implementación de proceso de bundling y minificación del modulo teacher-admin.mjs
  README.md
  dev-ops/build-application.sh
  dev-ops/bundle-teacher-module.sh
  ethicapp/.dockerignore
  ethicapp/frontend/assets/js/controllers/student/ethics_controller.js
  ethicapp/frontend/assets/js/controllers/student/role_controller.js
  ethicapp/frontend/assets/js/controllers/student/ses_controller.js
  ethicapp/frontend/assets/js/controllers/teacher/confirm_modal_controller.js
  ethicapp/frontend/views/ethics.ejs
  ethicapp/frontend/views/home.ejs
  ethicapp/frontend/views/partials/teacher/activities.html
  ethicapp/frontend/views/partials/teacher/designs.html
  ethicapp/frontend/views/roles.ejs
  ethicapp/frontend/views/seslist.ejs
  ethicapp/production.Dockerfile
  package.json
Labels: enhancement

#285 [ethicapp-v2] Issues #275, #276: Funcionalidades export chat csv y export asnwer csv rotas
  ethicapp/frontend/views/home.ejs
Labels: bug
